// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYx5An8AeXeTTgkXTS3zrIY5oKhrkqmZw',
    appId: '1:98421763105:web:4bb315cc80bfafa92dc760',
    messagingSenderId: '98421763105',
    projectId: 'unhingedcards-d866b',
    authDomain: 'unhingedcards-d866b.firebaseapp.com',
    storageBucket: 'unhingedcards-d866b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC0GC0_j5_rNOr6zfMKqutGQSlUvjh9RA',
    appId: '1:98421763105:android:f0d2adffb04698b92dc760',
    messagingSenderId: '98421763105',
    projectId: 'unhingedcards-d866b',
    storageBucket: 'unhingedcards-d866b.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIGb6cWvc0F6j6YA7Cxx8Hl0woZ7H8G_g',
    appId: '1:98421763105:ios:597d79442490ba122dc760',
    messagingSenderId: '98421763105',
    projectId: 'unhingedcards-d866b',
    storageBucket: 'unhingedcards-d866b.firebasestorage.app',
    iosBundleId: 'com.example.unhingedapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYx5An8AeXeTTgkXTS3zrIY5oKhrkqmZw',
    appId: '1:98421763105:web:30f1db90d6c0f6fb2dc760',
    messagingSenderId: '98421763105',
    projectId: 'unhingedcards-d866b',
    authDomain: 'unhingedcards-d866b.firebaseapp.com',
    storageBucket: 'unhingedcards-d866b.firebasestorage.app',
  );
}
